### ISSUE TITLE
Bug in swell create cli

### ISSUE THREAD

**Issue by asewnath** [GEOS-ESM/swell#390]
When running the cli option during the swell create step for hofx, the following error is thrown:

```
Traceback (most recent call last):
  File "/discover/nobackup/asewnath/JediOpt/core/swell/swell/bin/swell", line 10, in <module>
    sys.exit(main())
  File "/discover/nobackup/asewnath/JediOpt/core/swell/swell/lib/python3.10/site-packages/swell/swell.py", line 229, in main
    swell_driver()
  File "/gpfsm/dswdev/jcsda/spack-stack/scu16/spack-stack-1.7.0/envs/ue-intel-2021.6.0/install/intel/2021.6.0/py-click-8.1.7-5ucqhac/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/gpfsm/dswdev/jcsda/spack-stack/scu16/spack-stack-1.7.0/envs/ue-intel-2021.6.0/install/intel/2021.6.0/py-click-8.1.7-5ucqhac/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/gpfsm/dswdev/jcsda/spack-stack/scu16/spack-stack-1.7.0/envs/ue-intel-2021.6.0/install/intel/2021.6.0/py-click-8.1.7-5ucqhac/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/gpfsm/dswdev/jcsda/spack-stack/scu16/spack-stack-1.7.0/envs/ue-intel-2021.6.0/install/intel/2021.6.0/py-click-8.1.7-5ucqhac/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gpfsm/dswdev/jcsda/spack-stack/scu16/spack-stack-1.7.0/envs/ue-intel-2021.6.0/install/intel/2021.6.0/py-click-8.1.7-5ucqhac/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/discover/nobackup/asewnath/JediOpt/core/swell/swell/lib/python3.10/site-packages/swell/swell.py", line 107, in create
    create_experiment_directory(suite, input_method, platform, override, advanced, slurm)
  File "/discover/nobackup/asewnath/JediOpt/core/swell/swell/lib/python3.10/site-packages/swell/deployment/create_experiment.py", line 153, in create_experiment_directory
    experiment_dict_str = prepare_config(suite, method, platform, override, advanced, slurm)
  File "/discover/nobackup/asewnath/JediOpt/core/swell/swell/lib/python3.10/site-packages/swell/deployment/create_experiment.py", line 82, in prepare_config
    experiment_dict, comment_dict = prepare_config_and_suite.ask_questions_and_configure_suite()
  File "/discover/nobackup/asewnath/JediOpt/core/swell/swell/lib/python3.10/site-packages/swell/deployment/prepare_config_and_suite/prepare_config_and_suite.py", line 481, in ask_questions_and_configure_suite
    self.ask_a_question(self.question_dictionary_model_dep[model], question_key,
  File "/discover/nobackup/asewnath/JediOpt/core/swell/swell/lib/python3.10/site-packages/swell/deployment/prepare_config_and_suite/prepare_config_and_suite.py", line 540, in ask_a_question
    self.config_client.get_answer(question_key, qd)
  File "/discover/nobackup/asewnath/JediOpt/core/swell/swell/lib/python3.10/site-packages/swell/deployment/prepare_config_and_suite/question_and_answer_cli.py", line 47, in get_answer
    options = val['options']
KeyError: 'options'
```

The cli fails with this val dictionary:
```
val:  {'ask_question': False, 
       'default_value': '-PT3H', 
       'models': ['all'], 
       'prompt': 'What is the duration from the middle of the window when forecasts start?', 
       'tasks': ['GetBackground', 'LinkGeosOutput', 'MoveDaRestart', 'PrepareAnalysis', 'StoreBackground'], 
       'type': 'string-check-list'}
```

The type is set to `string-check-list` but there’s no explicit option for `string-check-list` in `question_and_answer_cli.py`. It tries to use the `check-list` option, but then this tries to access the `option` keyword from val, which is non-existent.

**Comment by asewnath** [comment]
Looking at the configurations for the different models, it looks like `geos-ocean` correctly has `options` keyword for anything listed as type `string-check-list` but `geos-atmosphere` is missing it in a few places.

**Comment by asewnath** [comment]
Another error is thrown on question `What is the duration from the middle of the window when forecasts start?` :

```
    self.config_client.get_answer(question_key, qd)
  File "/discover/nobackup/asewnath/JediOpt/core/swell/swell/lib/python3.10/site-packages/swell/deployment/prepare_config_and_suite/question_and_answer_cli.py", line 48, in get_answer
    answer = self.make_check_widget(quest, options, default, questionary.checkbox)
  File "/discover/nobackup/asewnath/JediOpt/core/swell/swell/lib/python3.10/site-packages/swell/deployment/prepare_config_and_suite/question_and_answer_cli.py", line 171, in make_check_widget
    answer = prompt(quest, choices=choices, default=default,
  File "/discover/nobackup/asewnath/JediOpt/core/swell/swell/lib/python3.10/site-packages/questionary/prompts/checkbox.py", line 132, in checkbox
    ic = InquirerControl(
  File "/discover/nobackup/asewnath/JediOpt/core/swell/swell/lib/python3.10/site-packages/questionary/prompts/common.py", line 237, in __init__
    raise ValueError(
ValueError: Invalid `default` value passed. The value (`-PT6H`) does not exist in the set of choices. Please make sure the default value is one of the available choices.
```

This error is because the default for `analysis_forecast_window_offset` in `geos-ocean` has `-PT6H` listed as a default, but `-PT6H` is not listed as an available option.
